### ISSUE TITLE
Missing history on master branch

### ISSUE THREAD

**Issue by periodic1236** [trezor/python-mnemonic#10]
#6 and #7 are currently missing from the commits on master even though they were merged. It seems like a forced update was done in the last month.

You should probably rebase c48303b and all subsequent commits onto 9941049, which was made as part of #7 (although I don't know if there are any commits with 9941049 as parent that were lost).

**Comment by prusnak** [comment]
I don't know what happened here, but as tests are green I am closing this issue.

Feel free to send a pull request if something else is missing.
