### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by prusnak** [trezor/python-mnemonic#111]
The last version 0.20 has been released in July 2021

Since then lot of smaller improvements has landed to master.

Should we release them as 0.21? @matejcik do you seen any blockers? If not, I can cut a new release to PyPI. just let me know what you think ...

**Comment by matejcik** [comment]
also this? https://github.com/trezor/python-mnemonic/pull/106

**Comment by matejcik** [comment]
other than that I'd go ahead.
this would be nice https://github.com/trezor/python-mnemonic/pull/94 but it's not ready, if you feel like finishing it then go ahead :woman_shrugging: otherwise i'd keep it open

**Comment by prusnak** [comment]
> hm, it seems that [71cf520](https://github.com/trezor/python-mnemonic/commit/71cf5203a2917694b6a030c9149506e643e8e0ec) introduced failure in the CI :-/

I reverted this commit for the time being to fix the CI

**Comment by matejcik** [comment]
release 0.21 is out
