### ISSUE TITLE
Feature request: Create combination of mnemo.check and mnemo.to_seed for optimal performance

### ISSUE THREAD

**Issue by Anynomouss** [trezor/python-mnemonic#118]
Great library. 
I am using this library among others in a scripts to brute force the order of mnemonics (for treasure hunts).
Since I generate all orders of passwords, this means I have to use the mnemonic package twice:, 
I) to check if mnemonic is valid             (runtime 0.00097 seconds)
II) a second time to generate the seed  (runtime 0.00195 seconds)

I was wondering if it would be possible and make sense to combine the two, and as save up to 30% on total runtime for generating a valid seeds? 

E.g. 
`mnemo.to_seed(mnemonic, checksum=True)`

Which would return the seed if checksum is `True` and would return `False` if the  checksum fails. I am certain I am not the only one who uses this library and wants to get the maximum performance, in which case  combination of the check for valid checksum and seed generation step would make sense.

Let me know your thoughts on this.

**Comment by prusnak** [comment]
If you want max performance, you do not want to be using Python, but C for example.

**Comment by Anynomouss** [comment]
Good point. I can check if there is a wrapped C or rust mnemonic package in Python, or go native.
Still, the arguments hold, if someone can be made more efficient for users, there is not reasons not to do it.

**Comment by Anynomouss** [comment]
You are right, raising an error would make more sense. This is also what pybi39 did. 
I was considering making such a pull request but if you think there will hardly a performance boost, I will not spend time on it.
