### ISSUE TITLE
italian wordlist

### ISSUE THREAD

**Issue by the9ull** [trezor/python-mnemonic#13]
Hello,
I'm collecting a list of italian words to create the localized version of the wordlist. I'm using the rules of BIP 39 and I'm trying to select very different words (very different => at least 4 changes required to transform a word into another of the list).
Do you have some advises in order to agevolate the integration with your work? 
Thanks!
Best regards
Martino

**Comment by prusnak** [comment]
I saw that italian wordlist is already implemented.
