### ISSUE TITLE
Please add BIP32 xprv to test vectors.

### ISSUE THREAD

**Issue by dabura667** [trezor/python-mnemonic#15]
I understand BIP32 is not technically part of mnemonic generation, but there have been multiple occasions where someone has run vectors on BIP39 and run vectors on BIP32, then wonders why they are wrong and it turns out they didn't feed the seed from BIP39 into BIP32 correctly.

Seeing as Trezor uses the BIP39 in order to generate BIP32 xprv, I think it would help tremendously if you would include BIP32 xprv in each test vector.

Thank you.

**Comment by prusnak** [comment]
Fixed in b502451a33a440783926e04428115e0bed87d01f
