### ISSUE TITLE
UnicodeWarning when calling check()

### ISSUE THREAD

**Issue by dooglus** [trezor/python-mnemonic#29]
```
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mnemonic
>>> mnemonic.Mnemonic('english').check('error fragile gadget')
/usr/local/lib/python2.7/dist-packages/mnemonic/mnemonic.py:78: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if first in mnemo.wordlist:
True
>>> 
```

`mnemo.wordlist` is a list of strings, `first` is unicode. Python 2.7 is trying to convert the Japanese text in the wordlist to unicode using the default `ascii` codec and failing.

Maybe it would be better to normalize_string() on each word in the wordlist in `__init__()` when we first read the wordlist from disk.

**Comment by matejcik** [comment]
this problem doesn't seem to be applicable anymore and furthermore affects only Python 2, which is EOLing very soon anyway
