### ISSUE TITLE
test_mnemonic.py doesn't handle UTF-8 wordlists well

### ISSUE THREAD

**Issue by slush0** [trezor/python-mnemonic#32]
Although UTF-8 wordlist is valid by BIP39, there're some issues in acceptance tests in test_mnemonic.py. For example, using french dict (as accepted in BIP39 spec) fail to pass "Test of word prefixes", because unit test cannot handle multi-byte characters well. Following words actually differ in fourth position:

```
Test of word prefixes:
Duplicate prefix aér for words ['aérer', 'aéronef']
Duplicate prefix cré for words ['créature', 'créditer', 'crémeux']
```

**Comment by matejcik** [comment]
the test in question does not exist anymore
