### ISSUE TITLE
Japanese (and other language) test vectors are missing

### ISSUE THREAD

**Issue by iancoleman** [trezor/python-mnemonic#33]
[vectors.json](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) only contains English wordlists.

Considering this is the [reference implementation](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#reference-implementation) it would be handy to have a reference set of tests. There are [Japanese test vectors listed in the BIP39 document](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#test-vectors), but it would be good to see the reference implementation be useful as a complete reference.

**Comment by prusnak** [comment]
TBH i was never fond of localized wordlists. Feel free to send a pull request adding other wordlists and test vectors.

**Comment by PhamDiesel** [comment]
Is true sorry about that thank for your help

**Comment by G6KG** [comment]
from mnemonic import Mnemonic
ImportError: cannot import name 'Mnemonic' from partially initialized module 'mnemonic' (most likely due to a circular import) (/Users/mac/Projects/python/bitcoin/mnemonic/mnemonic.py)

Process finished with
