### ISSUE TITLE
Include a LICENSE file in the tarball

### ISSUE THREAD

**Issue by hegjon** [trezor/python-mnemonic#34]
The tarball hosted on Python Package Index is used as the source for repackage mnemonic as a RPM package in Fedora.

It would make it easier to redistribute mnemonic if the tarball included a LICENSE file.

See https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text for more details

**Comment by prusnak** [comment]
Can you send a pull request please?

**Comment by prusnak** [comment]
Closing
