### ISSUE TITLE
I made a PDF to make it easy to generate mneomics with d16 dice

### ISSUE THREAD

**Issue by loriopatrick** [trezor/python-mnemonic#40]
Not sure if this is the best place for it but I thought I'd share.

[words.pdf](https://github.com/trezor/python-mnemonic/files/918470/words.pdf)

**Comment by junderw** [comment]
the 4-8 bit checksum won't work.

**Comment by prusnak** [comment]
Unfortunately you are right :-/ Only 1 out of 256 24-word mnemonics are correct.
