### ISSUE TITLE
End user request: execute from command line.

### ISSUE THREAD

**Issue by bracklanna** [trezor/python-mnemonic#41]
I installed the package & can run the test_mnemonic.py & test_shamir.py scripts fine; they produce successful command line output.

How do I use mnemonic.py directly from the command line?

E.g. I want to do:

`  % echo "76DB6A517B1DBFE8D21F9C2701E8F92C1FDD3876A51E97A08FF24142BEDA2AD3"  |    python mnemonic.py  `

and obtain a wordlist output at the command line.  (64 ascii hex characters = 256 bits of entropy)

mnemonic.py produces no output at the command line. Am I doing something wrong or is there something missing, e.g. this is not designed to produce command-line output?

If it's trivial or easy to implement please revise so that the script can produce direct command-line output for people who want to run this in CLI-only environments.

Thanks.

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/python-mnemonic/commit/094c4f4939dc6b5097575b787332f73d47759043

Example:

```
$ python mnemonic.py 76DB6A517B1DBFE8D21F9C2701E8F92C1FDD3876A51E97A08FF24142BEDA2AD3
item swap nephew wage swim virtual embody vicious check aunt dinner flag worry order surround phrase nut afford wish little cloud home prize hybrid

$ echo 76DB6A517B1DBFE8D21F9C2701E8F92C1FDD3876A51E97A08FF24142BEDA2AD3 | python mnemonic.py
item swap nephew wage swim virtual embody vicious check aunt dinner flag worry order surround phrase nut afford wish little cloud home prize hybrid
```
