### ISSUE TITLE
Arbitrary length data - Data length should be one of the following: [16, 20, 24, 28, 32]

### ISSUE THREAD

**Issue by xkortex** [trezor/python-mnemonic#42]
I am trying to encode an SSH ECDSA key (162 bytes). When I pass a bytes object of my data to `mnem.to_mnemonic(data)`, I get 

`ValueError: Data length should be one of the following: [16, 20, 24, 28, 32]`

It's not clear from the documentation which function of the API I should be using. Nor, it's not clear why I am not able to encode arbitrary length data. 

Thanks,

**Comment by prusnak** [comment]
I think the error specifies it clearly that the input data should be only from the given possibilities. This library is an implementation of BIP-39 which is not supposed to be used for encoding arbitrary length data.
