### ISSUE TITLE
Can't use Shamir's secret sharing with 12/24 word seeds

### ISSUE THREAD

**Issue by mifunetoshiro** [trezor/python-mnemonic#46]
len(seed) is bigger than primes.keys() in shamir.py so you get an "Unknown data length" exception. Works fine with the example sentence "Shamir's Secret Sharing Scheme!" because it's 31 in length, but can't be used with real BIP39 examples.

**Comment by prusnak** [comment]
Don't use this code. It's not meant to be used for production. We are finalizing the new standard: https://github.com/satoshilabs/slips/blob/master/slip-0039.md and once this is stabilized, we'll add the code to this repo.
