### ISSUE TITLE
Backup Phrase recover

### ISSUE THREAD

**Issue by successhalf** [trezor/python-mnemonic#56]
12 word phrase, lowercase, with spaces between each word, to recover funds & transactions.
bulk i can't search by hand
I need a program to input 12 words phrase
output address | Private key
1F5qrDynCi5hXwcmK8XQemiL5jZjczUVtT | L51jsPUMtSH4t9mcdMb56Hff8rH73x5uDapRUMaKR6TcL4RaQPPQ
https://prnt.sc/mrigrn

**Comment by prusnak** [comment]
Our issue tracker is not a freelancing platform.
