### ISSUE TITLE
Protocol Question

### ISSUE THREAD

**Issue by araa47** [trezor/python-mnemonic#59]
Hi if I use this as the ETH derivation path prefix, what is the limit of accounts i can generate from a single mnemonic seed phrase? 

```
ETH_DERIVATION_PATH_PREFIX = "m/44'/60'/0'/"
for i in range(100):
    key = (mnemonic_utils.mnemonic_to_private_key(wordList, f"{ETH_DERIVATION_PATH_PREFIX}{i}"))
```

**Comment by matejcik** [comment]
each path segment can be either 0 to (2**31 - 1) (0-2147483647) unhardened, or 0 to (2**31 - 1) hardened
