### ISSUE TITLE
Issue with french wordlist accents

### ISSUE THREAD

**Issue by vincentdnl** [trezor/python-mnemonic#60]
I think there is an issue with the french wordlist and accents on letters.

If you take the first word with an accent in the list: `académie` (line 19 in [this file](https://github.com/trezor/python-mnemonic/blob/master/mnemonic/wordlist/french.txt))

The `é` in this library is actually composed of `e` (U+0065 LATIN SMALL LETTER E) and `◌́` (U+0301 COMBINING ACUTE ACCENT).

On french keyboards (AZERTY layout), `é` as displayed under key "2" is a different character (U+00C9 LATIN SMALL LETTER E WITH ACUTE).

I think that the french wordlist `é` should be the same as the one on the keyboard. If you have to type your mnemonic on a keyboard you will be using the keyboard letter, not the one with the modifier.

Maybe I missed something but I think the right thing to do is to switch the U+0065 and U+0301 with U+00C9 on `french.txt`. I can make a pull request to fix this if you are interested.

Edit: it also fails for e with grave

Example code:

```python
>>> s = mnemonic.Mnemonic("french").generate()
>>> s
'brèche wagon image doyen garantir subtil adhésif asphalte invoquer homard inonder huileux'
>>> s.split()[0] == "brèche"
False
```

**Comment by sblondon** [comment]
If the problem can't be fixed due to backward compatibility, perhaps it could be mitigated for future use by providing a french file without accent?

**Comment by matejcik** [comment]
the wordlist is stored in Unicode [NFKD](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms) -- [as specified](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#Wordlist) in BIP-39.
If you want to compare strings you got somewhere outside, you need to call `Mnemonic.normalize_string`:
```python
In [1]: from mnemonic import Mnemonic                                                                        

In [2]: echarpe = "\u00e9charpe"                                                                             

In [3]: echarpe                                                                                              
Out[3]: 'écharpe'

In [4]: french = Mnemonic("french")                                                                          

In [5]: french.to_mnemonic(b"1" * 16)                                                                        
Out[5]: 'cigogne kimono écharpe falaise asservir méditer pupitre cabanon cigogne kimono écharpe farine'

In [6]: echarpe_nfkd = french.to_mnemonic(b"1" * 16).split(" ")[2]                                           

In [7]: echarpe_nfkd                                                                                         
Out[7]: 'écharpe'

In [8]: echarpe == echarpe_nfkd                                                                              
Out[8]: False

In [9]: Mnemonic.normalize_string(echarpe)                                                                   
Out[9]: 'écharpe'

In [10]: Mnemonic.normalize_string(echarpe) == echarpe_nfkd                                                  
Out[10]: True
```
