### ISSUE TITLE
Make new PyPi release

### ISSUE THREAD

**Issue by beardog108** [trezor/python-mnemonic#61]
Hi,

I noticed that in [this commit](https://github.com/trezor/python-mnemonic/commit/063a33b517803c88d81e0ff0ccc9587b833d8280) the external pbkdf2 dependency was rightly dropped.

However, the code on [PyPi](https://pypi.org/project/mnemonic/) still has the dependency even on the latest release there (0.18).

I would like to use mnemonic from PyPi without forcing my project to also require pbkdf2 as a child dependency.

I would appreciate it if someone could take a bit to make sure everything is ready and push a new release to PyPi.

Don't forget to bump the version, **it appears the dependency was removed without bumping the setup.py version on this repo**

![screenshot](https://i.imgur.com/tDUO1ZI.png)

**Comment by QuestofIranon** [comment]
Any status update on this?

**Comment by matejcik** [comment]
fixed as of https://github.com/trezor/python-mnemonic/releases/tag/v0.19
