### ISSUE TITLE
Feature request: Distribute type annotations

### ISSUE THREAD

**Issue by hukkinj1** [trezor/python-mnemonic#72]
How would you feel about type annotating the public API and distributing type information (via https://www.python.org/dev/peps/pep-0561/ )

Would a PR be welcome?

**Comment by matejcik** [comment]
I'd support adding inline type information. WRT distribution, if i'm reading this correctly, we'd have to add an empty `py.typed` file to the package? Which is also acceptable.

I'd be against creating and maintaining stubs separately.

**Comment by hukkinj1** [comment]
Added inline type annotations in https://github.com/trezor/python-mnemonic/pull/73

> if i'm reading this correctly, we'd have to add an empty py.typed file to the package?

yes exactly
