### ISSUE TITLE
to_entropy function return 'Failed checksum'

### ISSUE THREAD

**Issue by dcordi** [trezor/python-mnemonic#80]
Hi,

I try mnemonic and bitcoinlib and i found this problem.

C:\temp>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> **import mnemonic**
>>> **lang = mnemonic.Mnemonic('english')**

>>> **lang.to_entropy('mother derive history rapid clean donor nature desert pair dolphin tower volume')**
bytearray(b"\x90\'m\xb0\xd8\xf2\xa4\x82\xa4\xd9\xdd\x9f\x08\x1b\x98\xfa")

>>> **lang.to_entropy('mother derive history rapid clean donor nature desert pair dolphin volume tower')**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\mnemonic\mnemonic.py", line 173, in to_entropy
    raise ValueError("Failed checksum.")
ValueError: Failed checksum.

>>>

The only thing i did was reverse the last 2 words.

Why reversing 2 words created an exception in the to_entropy () function?

Thank's

**Comment by prusnak** [comment]
Read BIP39 to understand that the words contain the checksum.
