### ISSUE TITLE
Use of native random function to generate seed phrase

### ISSUE THREAD

**Issue by lolero** [trezor/python-mnemonic#81]
Good morning!

I wanted to ask if the following would be a proper and safe approach to generating a seed phrase, as opposed to using the generate function in the `mnemonic` class:

 - use the native python random function to pick the first 23 words of the seed phrase
 - iterate over all 2048 words in the word list to find the 8 valid options for the 24th word
 - use the native python random function again to pick one of the valid 8 seed phrases

Thank you!

**Comment by prusnak** [comment]
Yes, this sounds safe.
