### ISSUE TITLE
 cannot import name 'Mnemonic' from 'mnemonic' 

### ISSUE THREAD

**Issue by jdjfd** [trezor/python-mnemonic#86]
- pip installed version 0.20

- `from mnemonic import Mnemonic`

- ImportError: cannot import name 'Mnemonic' from 'mnemonic'

what are the issues that might cause this? any requirements?

**Comment by prusnak** [comment]
How did you install python-mnemonic? Using `pip install`?

**Comment by jdjfd** [comment]
seems issue happened because i installed it in the wrong directory?  closed thanks.
