### ISSUE TITLE
Feature: More reliable detection of mnemonic language

### ISSUE THREAD

**Issue by moneymanolis** [trezor/python-mnemonic#98]
There is an overlap of 100 words in the English and French BIP39 wordlists, thus when using the current `detect_language` method in a code snippet like this ...
```
    language = Mnemonic.detect_language(mnemonic)
    mnemo = Mnemonic(language)
    wordlist = mnemo.wordlist
```
... it can happen that the French wordlist _(abaisser, abandon, abdiquer, ...)_
 is used whereas the original mnemonic was actually an English one _(abandon, knee, cruel ... )_

Perhaps, it would be as easy as checking the first two or three seed words to determine the language instead of just the first one here:
https://github.com/trezor/python-mnemonic/blob/6b7ebdb3624bbcae1a7b3c5485427a5587795120/src/mnemonic/mnemonic.py#L110

@prusnak what do you think?

**Comment by moneymanolis** [comment]
Alright, thanks for the reply. Let's leave it like this then and we just drop French as a supported language for the hot wallet feature in Specter. Spanish works well (no overlaps there) which should be the most important language besides English.

**Comment by pjkundert** [comment]
Hi, @prusnak.  I don't think this should be closed...

This is not an efficiency or style issue -- this is a correctness issue.

Incorrect detection of language, when the correct language can be trivially and reliably detected, is worth fixing, IMHO.

I'll work up a pull request, and get your comments.
